### ISSUE TITLE
Need proper handling of R_PPC_REL24 / R_PPC_JMP_SLOT in terms of sobjs support (old "st_value = 0" patch)

### ISSUE THREAD

**Issue by kas1e** [migthymax/binutils-gdb#13]
After some tests, we find out that anything using .sojbs just crashes for us, and the issue was that originally  ```st_value``` is set to 0 in bfd's code, while in old adtool's binutils this commented out, to avoid some issues with bug in elf.library. There is relevant part from old adtools's binutils:

```
-          sym->st_value = 0;
+          {
+            /* THF: This is peculiar. The compiler generates a R_PPC_REL24 for externally referenced
+             * symbols impoted from libc.so. Relocation in elf.library requires the symbol to have it's .plt
+             * stub value, but the linker specifically clears the value to 0, resulting in run-time
+             * errors when the binary tries to call libc functions.
+             */
+            // sym->st_value = 0;
+                  }
```

Yes, It is a bad that this "fix" was placed in binutils, instead of fixing elf.library. Now, once elf.library will be fixed, this "st_value" set to 0, will be working when need it and handled correctly, but to have everything working and with previous old versions of unfixed elf.lirbary, we had to add that "fix" again. Just in some proper way.

**Comment by migthymax** [comment]
(copied from [adtools port](https://github.com/sba1/adtools))
```
This is peculiar. The compiler generates a R_PPC_JMP_SLOT for externally referenced
symbols imported from libc.so. Relocation in elf.library requires the symbol to have it's .plt
stub value, but the linker specifically clears the value to 0, resulting in run-time
errors when the binary tries to call libc functions.
```

Doing so breaks the function address equality between sobjs! The [chapter 4.3.3 of e500 PPC ABI](https://www.nxp.com/docs/en/reference-manual/E500ABIUG.pdf) explicitly states that a zero value must be supported to enable that.
But the current available dynamic linker (elf.library version 53.30) cannot handle a value of zero and crashes.

As long no public dynamic linker is available, which can handle this case, this patch will be included. As soon the dynamic linker can handle this, the patch will be removed. So that the following issue even can be resolved: [Template function argument changes address btw main exe and from inside shared object](https://github.com/sba1/adtools/issues/109)

For mores interesting insight see the following discussions on [amigans](https://amigans.net)
* [Qt 6 progress](https://www.amigans.net/modules/newbb/viewtopic.php?topic_id=8595)
* [gcc 9 and 10](https://www.amigans.net/modules/newbb/viewtopic.php?topic_id=8408)
